### PR TITLE
feat: v:run auto remove build file

### PR DESCRIPTION
**Pull request by d1y**
Only tested on my mac, Thank you vlang team

### CODE REVIEW

**Comment by danieldaeschle** [comment]
not sure about this. is it really needed?

**Comment by d1y** [comment]
> not sure about this. is it really needed?
> 
> _i will think about it_

Well, it is necessary, basically every time these binary files are accidentally added to .git

This confuses me, because of this reason, I give up using v language to develop

**Comment by spaceface777** [comment]
> every time these binary files are accidentally added to .git

`.gitignore` exists for a reason, you can tell git to ignore any binary files automatically.

Plus, what version of V are you using? This specific issue was fixed in V itself in vlang/v@fbf6910.

**Comment by danieldaeschle** [comment]
> > not sure about this. is it really needed?
> > _i will think about it_
> 
> Well, it is necessary, basically every time these binary files are accidentally added to .git
> 
> This confuses me, because of this reason, I give up using v language to develop

you stopped developing in V because it genereates a binary in your workspace? well, that's hard :D

**Comment by nedpals** [comment]
Closed. I suggest to use install the latest version of V for this.

**Pull request closed without merging**
