### PR TITLE
[DEPS] Update Dependencies  (2)

### PR DESCRIPTION
**Pull request by felixf4xu**
This is a continued PR based on #497 

based on that, 
1) more dependencies' version is updated,  this should close #520, #521, and #524
2) code fixes for #530 and #532, at lease with these 2 fixes, local `npm run package` will success.

### CODE REVIEW

**Comment by tobealive** [comment]
Hey @felixf4xu,

thanks for your efforts! 

to cite from https://github.com/vlang/vls/pull/446 about the current vls situation:
> VLS is in the middle of a HUGE re-write, the repo is private atm, but it will be released in July:
>
> https://github.com/v-analyzer
>
> this re-write works great, vlang/vls is currently archived

To make sure your work can be even utilised, maybe wait for a response of the new v analyzer dev.

**Comment by felixf4xu** [comment]
@tobealive is that only for `vls`, or same for this vscode extension?

**Comment by i582** [comment]
> @tobealive is that only for `vls`, or same for this vscode extension?

For both

**Comment by felixf4xu** [comment]
Good to know that, also nice to see its new start.

**Pull request closed without merging**
