### PR TITLE
Added i32 as a type for syntax highlight

### PR DESCRIPTION
**Pull request by txgruppi**
I think the title says it all

### CODE REVIEW

**Comment by JalonSolov** [comment]
Right now, i32 is a type alias, not a "real" type.

**Comment by txgruppi** [comment]
@JalonSolov but it is still a type. Why not highlight it as one.

I think this is not a dicussion to have in this repo but shouldn't `i32` by the concrete type and `int` the alias. After all we have `i8`, `i16`, and `i64`.

**Comment by txgruppi** [comment]
@JalonSolov I updated the PR to only include `i32` in the numeric type list. Same place where `u8` is defined. This should fix `i32` being the _different one_.

image

**Comment by txgruppi** [comment]
any news on this one?

**Comment by Sarctiann** [comment]
hello @txgruppi I recommend you talk about this on Discord https://discord.gg/2gnC8YK4qC
There is no channel for vscode-vlang but for vls and ideas-suggestions... The whole team is here. so I think it will be the fastest way to reach a resolution

**Comment by JalonSolov** [comment]
`u8` has been switched to the real type, with `byte` as an alias.  Nothing has changed with `i32` vs `int`, yet.

**Pull request closed without merging**
