### PR TITLE
install vls automatically

### PR DESCRIPTION
**Pull request by danieldaeschle**

### CODE REVIEW

**Comment by donnisnoni** [comment]
Are you sure using git?

**Comment by JalonSolov** [comment]
While most people do have git, it isn't available by default on Windows at all, and it is only installed by default on _some_ linux distributions.  If this is expected to work everywhere vscode does, a different strategy will be needed, or it will have to mention in the message that you must have git installed for it to work.

**Comment by donnisnoni** [comment]
Agree with my sir @JalonSolov !!

**Comment by danieldaeschle** [comment]
`v install` will be used later.

**Comment by tomByrer** [comment]
Hard to imagine more than 5% of people do not have git installed for one reason or another.
This is just a convince anyhow, that 5% can install VLS manually, correct?

**Comment by danieldaeschle** [comment]
We will release binaries. Not sure if it's needed currently.

**Comment by danieldaeschle** [comment]
for now, v install should work.

**Review by nedpals — APPROVED** [review]

**Pull request merged**
